export const KONSTRUKSI_OPTIONS = [
	{ key: "TR_1", label: "TR-1" },
	{ key: "TR_1_SUPP", label: "TR-1 + SUPP" },
	{ key: "TR_2", label: "TR-2" },
	{ key: "TR_3", label: "TR-3" },
	{ key: "TR_3A", label: "TR-3A" },
	{ key: "TR_4", label: "TR-4" },
	{ key: "TR_4A", label: "TR-4A" },
	{ key: "TR_4B", label: "TR-4B" },
	{ key: "TR_5", label: "TR-5" },
	{ key: "TR_5_SUPP", label: "TR-5 + SUPP" },
	{ key: "TR_6", label: "TR-6" },
	{ key: "TR_6A", label: "TR-6A" },
	{ key: "TR_7", label: "TR-7" },
	{ key: "TR_8", label: "TR-8" },
	{ key: "TR_9", label: "TR-9" },
];

export const KONSTRUKSI_PRESETS = {
	TR_1: [
		{ name: "Suspension Clamp Bracket", unit: "Set", qty: 1 },
		{ name: "Suspension Clamp", unit: "Set", qty: 1 },
		{ name: "Stainless Steel Strip 0,75 Mtr", unit: "Pcs", qty: 2 },
		{ name: "Stopping Buckle", unit: "Pcs", qty: 2 },
		{ name: "Plastic Strap", unit: "Pcs", qty: 3 },
		{ name: "Bundle 35 mm – 50 cm (kumisan) + Tanda Phasa", unit: "Set", qty: 4 },
		{ name: "Line Tap Connector 70-50 + Heatshrink", unit: "Set", qty: 4 },
	],
	TR_2: [
		{ name: "Tension Bracket", unit: "Set", qty: 1 },
		{ name: "Strain Clamp", unit: "Set", qty: 2 },
		{ name: "Stainless Steel Strip 0,75 Mtr", unit: "Pcs", qty: 2 },
		{ name: "Stopping Buckle", unit: "Pcs", qty: 2 },
		{ name: "Plastic Strap", unit: "Pcs", qty: 3 },
		{ name: "Bundle 35 mm – 50 cm (kumisan) + Tanda Phasa", unit: "Set", qty: 4 },
		{ name: "Line Tap Connector 70-50 + Heatshrink", unit: "Set", qty: 4 },
	],
	TR_3A: [
		{ name: "Tension Bracket", unit: "Set", qty: 1 },
		{ name: "Strain Clamp", unit: "Set", qty: 1 },
		{ name: "Stainless Steel Strip 0,75 Mtr", unit: "Pcs", qty: 2 },
		{ name: "Stopping Buckle", unit: "Pcs", qty: 2 },
		{ name: "Plastic Strap", unit: "Pcs", qty: 2 },
		{ name: "Bundle 35 mm – 50 cm (kumisan) + Tanda Phasa", unit: "Set", qty: 4 },
		{ name: "Line Tap Connector 70-50 + Heatshrink", unit: "Set", qty: 4 },
	],
	TR_7: [
		{ name: "Tension Bracket", unit: "Set", qty: 1 },
		{ name: "Strain Clamp", unit: "Set", qty: 1 },
		{ name: "Stainless Steel Strip 0,75 Mtr", unit: "Pcs", qty: 2 },
		{ name: "Stopping Buckle", unit: "Pcs", qty: 2 },
		{ name: "Plastic Strap", unit: "Pcs", qty: 2 },
		{ name: "Compresiont Connector All. 70 / 50", unit: "Pcs", qty: 4 },
		{ name: "Bundle 50 mm – 50 cm (kumisan) + Tanda Phasa", unit: "Set", qty: 4 },
		{ name: "Line Tap Connector 70-50 + Heatshrink", unit: "Set", qty: 4 },
		{ name: "Bundle 35 mm – 50 cm (kumisan) + Tanda Phasa", unit: "Set", qty: 4 },
	],
	TR_7: [
		{ name: "LV Pin Insulator S1", unit: "Set", qty: 4 },
		{ name: "Cross Arm type 1200 NP-10", unit: "Pcs", qty: 1 },
		{ name: "Preformed Termination", unit: "Pcs", qty: 4 },
		{ name: "Single Arm Band", unit: "Set", qty: 2 },
		{ name: "Conductor 70 mm", unit: "ms", qty: 40 },
	],
	TR_1_SUPP: [
		{ name: "Suspension Clamp Bracket", unit: "Set", qty: 1 },
		{ name: "Suspension Clamp", unit: "Set", qty: 1 },
		{ name: "Stainless Steel Strip 0,75 Mtr", unit: "Pcs", qty: 2 },
		{ name: "Stopping Buckle", unit: "Pcs", qty: 2 },
		{ name: "Plastic Strap", unit: "Pcs", qty: 3 },
		{ name: "Bundle 35 mm – 50 cm (kumisan) + Tanda Phasa", unit: "Set", qty: 4 },
		{ name: "Line Tap Connector 70-50 + Heatshrink", unit: "Set", qty: 4 },
	],
	
	TR_5_SUPP: [
		{ name: "Tension Bracket", unit: "Set", qty: 2 },
		{ name: "Strain Clamp", unit: "Set", qty: 2 },
		{ name: "Stainless Steel Strip 0,75 Mtr", unit: "Pcs", qty: 2 },
		{ name: "Stopping Buckle", unit: "Pcs", qty: 2 },
		{ name: "Plastic Strap", unit: "Pcs", qty: 3 },
		{ name: "Bundle 35 mm – 50 cm (kumisan) + Tanda Phasa", unit: "Set", qty: 4 },
		{ name: "Line Tap Connector 70-50 + Heatshrink", unit: "Set", qty: 4 },
	],
	TR_5: [
		{ name: "Tension Bracket", unit: "Set", qty: 2 },
		{ name: "Strain Clamp", unit: "Set", qty: 2 },
		{ name: "Stainless Steel Strip 0,75 Mtr", unit: "Pcs", qty: 2 },
		{ name: "Stopping Buckle", unit: "Pcs", qty: 2 },
		{ name: "Plastic Strap", unit: "Pcs", qty: 3 },
		{ name: "Bundle 35 mm – 50 cm (kumisan) + Tanda Phasa", unit: "Set", qty: 4 },
		{ name: "Line Tap Connector 70-50 + Heatshrink", unit: "Set", qty: 4 },
	],
	TR_3: [
		{ name: "Tension Bracket", unit: "Set", qty: 1 },
		{ name: "Strain Clamp", unit: "Set", qty: 1 },
		{ name: "Stainless Steel Strip 0,75 Mtr", unit: "Pcs", qty: 4 },
		{ name: "Stopping Buckle", unit: "Pcs", qty: 4 },
		{ name: "Plastic Strap", unit: "Pcs", qty: 2 },
		{ name: "PVC 2” – 50 Cm", unit: "Pcs", qty: 1 },
		{ name: "Link", unit: "Pcs", qty: 2 },
		{ name: "Dead End Tubes", unit: "Pcs", qty: 4 },
		{ name: "Bundled 35mm - 50cm (kumisan) + Tanda Phasa", unit: "Set", qty: 4 },
		{ name: "Line Tap Connector 70-50 + Heatshrink", unit: "Set", qty: 4 },
	],
	TR_9: [
		{ name: "LV Pin Insulator S1", unit: "Set", qty: 4 },
		{ name: "Cross Arm type 1200 NP-10", unit: "Pcs", qty: 1 },
		{ name: "Preformed Termination", unit: "Pcs", qty: 4 },
		{ name: "Single Arm Band", unit: "Set", qty: 2 },
		{ name: "Conductor 70 mm", unit: "ms", qty: 40 },
		{ name: "Bolt & Nut M.16 x 120 mm", unit: "Pcs", qty: 4 },
		{ name: "Cross Arm Clevis/Suspension VEE", unit: "Pcs", qty: 4 },
		{ name: "Bolt & Nut M.16 x 110 mm", unit: "mtr", qty: 4 },
	],
	TR_6: [
		{ name: "Suspension Clamp Bracket", unit: "Set", qty: 1 },
		{ name: "Suspension Clamp", unit: "Set", qty: 1 },
		{ name: "Tension Bracket", unit: "Set", qty: 1 },
		{ name: "Strain Clamp", unit: "Set", qty: 1 },
		{ name: "Stainless Steel Strip 0,75 Mtr", unit: "Pcs", qty: 4 },
		{ name: "Stopping Buckle", unit: "Pcs", qty: 4 },
		{ name: "Plastic Strap", unit: "Pcs", qty: 5 },
		{ name: "Compression Connector All. 70/50", unit: "Pcs", qty: 4 },
		{ name: "Bundle 35 mm – 50 cm (kumisan) + Tanda Phasa", unit: "Set", qty: 4 },
		{ name: "Line Tap Connector 70-50 + Heatshrink", unit: "Set", qty: 4 },
	],
	TR_6A: [
		{ name: "Tension Bracket", unit: "Set", qty: 2 },
		{ name: "Strain Clamp", unit: "Set", qty: 3 },
		{ name: "Stainless Steel Strip 0,75 Mtr", unit: "Pcs", qty: 4 },
		{ name: "Plastic Strap", unit: "Pcs", qty: 5 },
		{ name: "Stopping Buckle", unit: "Pcs", qty: 4 },
		{ name: "Compriesion Connector All. 70/50", unit: "Pcs", qty: 4 },
		{ name: "Bundle 35 mm – 50 cm (kumisan) + Tanda Phasa", unit: "Set", qty: 4 },
		{ name: "Line Tap Connector 70-50 + Heatshrink", unit: "Set", qty: 4 },
	],
	TR_4: [
		{ name: "Suspension Clamp Bracket", unit: "Set", qty: 2 },
		{ name: "Suspension Clamp", unit: "Set", qty: 2 },
		{ name: "Stainless Steel Strip 0,75 Mtr", unit: "Pcs", qty: 4 },
		{ name: "Stopping Buckle", unit: "Pcs", qty: 4 },
		{ name: "Plastic Strap", unit: "Pcs", qty: 6 },
		{ name: "Compriesion Connector All. 70/50", unit: "Pcs", qty: 8 },
		{ name: "Bundle 35 mm – 50 cm (kumisan) + Tanda Phasa", unit: "Set", qty: 4 },
		{ name: "Line Tap Connector 70-50 + Heatshrink", unit: "Set", qty: 4 },
	],
	TR_4A: [
		{ name: "Tension Bracket", unit: "Set", qty: 1 },
		{ name: "Strain Clamp", unit: "Set", qty: 2 },
		{ name: "Stainless Steel Strip 0,75 Mtr", unit: "Pcs", qty: 4 },
		{ name: "Stopping Buckle", unit: "Pcs", qty: 4 },
		{ name: "Plastic Strap", unit: "Pcs", qty: 6 },
		{ name: "Compriesion Connector All. 70/50", unit: "Pcs", qty: 8 },
		{ name: "Suspension Clamp Bracket", unit: "Pcs", qty: 1 },
		{ name: "Suspension Clamp", unit: "Set", qty: 1 },
		{ name: "Bundle 35 mm – 50 cm (kumisan) + Tanda Phasa", unit: "Set", qty: 4 },
		{ name: "Line Tap Connector 70-50 + Heatshrink", unit: "Set", qty: 4 },
	],
	TR_4B: [
		{ name: "Tension Bracket", unit: "Set", qty: 2 },
		{ name: "Strain Clamp", unit: "Set", qty: 4 },
		{ name: "Stainless Steel Strip 0,75 Mtr", unit: "Pcs", qty: 4 },
		{ name: "Plastic Strap", unit: "Pcs", qty: 6 },
		{ name: "Stopping Buckle", unit: "Pcs", qty: 4 },
		{ name: "Compriesion Connector All. 70/50", unit: "Pcs", qty: 8 },
		{ name: "Bundle 35 mm – 50 cm (kumisan) + Tanda Phasa", unit: "Set", qty: 4 },
		{ name: "Line Tap Connector 70-50 + Heatshrink", unit: "Set", qty: 4 },
	],
};

// Harga satuan per set konstruksi dan harga jasa per set.
// Angka di bawah diambil dari tabel referensi yang Anda berikan.
// Satuan harga menggunakan satuan yang sama seperti modul lain (mis. Rupiah tanpa pemisah).
// Jika sebuah key tidak tercantum, dianggap belum memiliki harga (0).
export const KONSTRUKSI_PRICES = {
	TR_1: { unit: "Set", hargaSatuan: 89689, hargaJasa: 28974 },
	TR_2: { unit: "Set", hargaSatuan: 120241, hargaJasa: 57947 },
	TR_3: { unit: "Set", hargaSatuan: 185799, hargaJasa: 80242 },
	TR_4: { unit: "Set", hargaSatuan: 179377, hargaJasa: 57947 },
	TR_4A: { unit: "Set", hargaSatuan: 209929, hargaJasa: 86921 },
	TR_4B: { unit: "Set", hargaSatuan: 240482, hargaJasa: 115895 },
	TR_5: { unit: "Set", hargaSatuan: 113561, hargaJasa: 49255 },
	TR_3A: { unit: "Set", hargaSatuan: 0, hargaJasa: 0 }, // isi bila tersedia
	TR_6: { unit: "Set", hargaSatuan: 203250, hargaJasa: 78229 },
	TR_6A: { unit: "Set", hargaSatuan: 233802, hargaJasa: 107202 },
	TR_7: { unit: "Set", hargaSatuan: 113561, hargaJasa: 49255 },
};

